<template>
        <p class="px-8 py-16 text-center text-uppercase text-h4">Professional Projects</p>
        <Project flip image="motion.webp" title="AI motion control system for games" text="After the Kinect motion control device was discontinued, we started experimenting with different solutions for Rehaboo's exercise games. I took ownership of this project and built a software-only motion control system based on computer vision and cloud computing, enabling motion controlled games to be played on laptops and mobile devices with no additional hardware. All you need is a standard camera. In addition to detecting gestures, it can be used to match a 3D avatar to the player's pose in real-time, just like with Kinect. We were among the first companies in the world to develop this technology." />
        <Project image="active.jpg" title="Rehaboo! Active" text="An innovative exercise game for physical therapy, workplace activation and elderly care. Run, jump, squat and surf your way around obstacles or take an easy walk in the park while completing various minigames. The game is easy to configure for different use cases. At Rehaboo I was a generalist game developer with a focus on technology and AI. In addition to developing Rehaboo's motion control solution, I worked on gameplay code, mobile porting, shaders, optimization and 3D art." />
        <Project flip image="neurocar.jpg" title="Neurocar" text="A simulator and driving test platform designed to gather large amounts of cognitive and behavioural data. Neurocar is used by hospitals and vocational schools to assess a driver's attention, risk-taking behaviour and suitability for professional driving roles. It can be used to assess cognitive disorders and behavioral patterns, while traditional driving simulators focus more on teaching." />
        <Project image="atlas.webp" title="Cognitive Atlas" text="Backed by research conducted in the University of Basel, Cognitive Atlas is a platform designed to gather cognitive health data through simple web-based games. The games were built using Unity WebGL. I focused on backend design and integration through a GraphQL API." />
        <Project flip image="mobile.jpeg" title="Evok.eye" text="All of EvokAI's products gather vital data about the user's cognitive health. A comprehensive AI-powered data platform was designed to gather all of EvokAI's data into one place, where the user or their doctor can easily monitor progress. AI-powered tools within Evok.eye can be used to make predictions and summaries of the user's cognitive well-being. I have worked on all aspects of the platform from UI/UX to data analysis and backend development." />
</template>

<script setup>
  //
</script>